# -*- coding: utf-8 -*-
"""Bart model summarizing.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1haC7xzgRpNQ1Z4AmxrPs-azl6Hjp74cu
"""

def f_summarize(input_text):
    from transformers import BartTokenizer
    tokenizer = BartTokenizer.from_pretrained('facebook/bart-large-cnn')
    from transformers import BartForConditionalGeneration
    model = BartForConditionalGeneration.from_pretrained('facebook/bart-large-cnn')
    text = input_text
    tokens = tokenizer(text, truncation=True, padding="longest", return_tensors="pt")
    summary = model.generate(**tokens,max_length= 300,min_length=300)
    res = tokenizer.decode(summary[0])
    return res